<script type="text/javascript">
    require([
        'jquery',
        'underscore'
    ], function ($, _) {
        if (typeof window.digitalData !== 'object') {
            return;
        }

        /**
         * Events listener
         */
        $(document).on('ajaxComplete', function (event, xhr, settings) {
            if (settings.url.indexOf('customer/section/load') <= -1 || !_.isObject(xhr.responseJSON)) {
                return;
            }

            if (typeof xhr.responseJSON.ddl_cart === 'object') {
                if (typeof window.digitalData.cart === 'object' || xhr.responseJSON.ddl_cart.lineItems.length > 0) {
                    if (typeof window.digitalData.cart === 'object'
                        && typeof window.digitalData.cart.checkoutStep === 'number'
                    ) {
                        xhr.responseJSON.ddl_cart.checkoutStep = window.digitalData.cart.checkoutStep;
                    }
                    window.digitalData.cart = xhr.responseJSON.ddl_cart;
                }
            }
        });
    });
</script>