<?php
/**
 * @var $block \Driveback\DigitalDataLayer\Block\Manager
 */
$projectId = $block->getProjectId();
?>
<!-- Digital Data Manager snippet -->
<script type="text/javascript">
    (function(e){var a=window.ddManager=window.ddManager||[];window.ddListener=window.ddListener||[];var b=window.digitalData=window.digitalData||{};b.events=b.events||[];if(!a.initialize)if(a.invoked)window.console&&console.error&&console.error("Digital Data Manager snippet included twice.");else{a.invoked=!0;a.methods="initialize addIntegration persist unpersist on once off".split(" ");a.factory=function(f){return function(){var c=Array.prototype.slice.call(arguments);c.unshift(f);a.push(c);return a}};
        for(b=0;b<a.methods.length;b++){var d=a.methods[b];a[d]=a.factory(d)}a.load=function(a){var c=document.createElement("script");c.type="text/javascript";c.async=!0;c.src=a;a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(c,a)};a.loadProject=function(b){var c=window.location.search;0<=c.indexOf("ddm_test_mode=1")?window.localStorage.setItem("_ddm_test_mode","1"):0<=c.indexOf("ddm_test_mode=1")&&window.localStorage.removeItem("_ddm_test_mode");b="1"===window.localStorage.getItem("_ddm_test_mode")?
        "//api.ddmanager.ru/v1/ddm-initialization/"+b+".js":"//cdn.ddmanager.ru/ddm-initialization/"+b+".js";a.load(b)};a.SNIPPET_VERSION="1.0.3";a.loadProject(e)}})("<?php echo $block->escapeJsQuote($projectId, '"') ?>");
</script>
<!-- //Digital Data Manager snippet -->